export type IssuedTicketStatus =
  | 'ISSUED'
  | 'USED'
  | 'CANCELLED'

export interface IssuedTicketResponse {
  id: string
  orderId: string
  userId: string
  eventId: string

  eventName?: string | null
  eventStartsAt?: string | null
  venueName?: string | null
  venueAddress?: string | null
  venueCity?: string | null
  venueTimezone?: string | null

  inventoryId: string

  sectionId?: string | null
  sectionName?: string | null
  sectionType?: string | null

  seatId?: string | null
  seatLabel?: string | null

  /**
   * Internal admission token assigned to the ticket.
   *
   * It remains part of the API response, but it should not be used
   * directly as the customer-facing QR code.
   */
  admissionToken: string

  status: IssuedTicketStatus
  issuedAt: string
  checkedInAt?: string | null
  checkedInByUserId?: string | null

  /**
   * Signed payload generated by Orders Service.
   *
   * This is the value that the check-in scanner sends back to
   * the backend for signature validation.
   */
  qrPayload?: string | null

  /**
   * SVG QR image encoded as a data URL by Orders Service.
   *
   * It can be assigned directly to an <img src="..."> element.
   */
  qrDataUrl?: string | null
}