import { useMemo, useState } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { eventsApi } from '../../api/eventsApi'
import { commerceApi } from '../../api/commerceApi'
import { ErrorState, Loading } from '../../components/Ui'
import { formatMoney } from '../../lib/format'

export function CommercePage(){
 const qc=useQueryClient(); const events=useQuery({queryKey:['events'],queryFn:eventsApi.getEvents}); const [eventId,setEventId]=useState('');
 const selected=eventId || events.data?.[0]?.id || ''; const selectedEvent=events.data?.find(e=>e.id===selected); const sections=useQuery({queryKey:['sections',selectedEvent?.venueId],queryFn:()=>eventsApi.getSections(selectedEvent!.venueId),enabled:Boolean(selectedEvent)}); const analytics=useQuery({queryKey:['analytics',selected],queryFn:()=>commerceApi.analytics(selected),enabled:Boolean(selected)}); const tiers=useQuery({queryKey:['pricing-tiers',selected],queryFn:()=>commerceApi.pricingTiers(selected),enabled:Boolean(selected)}); const promos=useQuery({queryKey:['promotions'],queryFn:commerceApi.promotions});
 const [tierName,setTierName]=useState('Preventa');const [tierPrice,setTierPrice]=useState('0');const [sectionId,setSectionId]=useState('');const [salesStartAt,setSalesStartAt]=useState('');const [salesEndAt,setSalesEndAt]=useState('');const [code,setCode]=useState('');const [discount,setDiscount]=useState('10');
 const addTier=useMutation({mutationFn:()=>commerceApi.createPricingTier(selected,{sectionId,name:tierName,price:tierPrice,currency:'MXN',salesStartAt:salesStartAt?new Date(salesStartAt).toISOString():null,salesEndAt:salesEndAt?new Date(salesEndAt).toISOString():null,priority:10,active:true}),onSuccess:()=>qc.invalidateQueries({queryKey:['pricing-tiers',selected]})});
 const addPromo=useMutation({mutationFn:()=>commerceApi.createPromotion({code,description:'Promoción TicketFlow',discountType:'PERCENTAGE',discountValue:discount,eventId:selected||null,startsAt:null,endsAt:null,maxUses:null,maxUsesPerUser:1,active:true}),onSuccess:()=>qc.invalidateQueries({queryKey:['promotions']})});
 const error=events.error||analytics.error||tiers.error||promos.error||addTier.error||addPromo.error; if(events.isPending)return <Loading/>;
 const a=analytics.data; return <section><div className="page-heading"><div><span className="eyebrow">Revenue management</span><h2>Ventas, pricing y promociones</h2><p>Control comercial por evento sin modificar compras históricas.</p></div></div>{error instanceof Error&&<ErrorState error={error}/>}<div className="panel"><label>Evento<select value={selected} onChange={e=>setEventId(e.target.value)}>{events.data?.map(e=><option key={e.id} value={e.id}>{e.name}</option>)}</select></label></div>
 {a&&<div className="stat-grid"><article className="panel"><small>INGRESO NETO</small><h2>{formatMoney(a.netRevenue,'MXN')}</h2></article><article className="panel"><small>BOLETOS VENDIDOS</small><h2>{a.ticketsSold}</h2></article><article className="panel"><small>CHECK-INS</small><h2>{a.ticketsCheckedIn}</h2></article><article className="panel"><small>REFUNDS</small><h2>{a.ticketsRefunded}</h2></article></div>}
 <div className="two-column"><section className="panel"><h3>Price tiers</h3><div className="form-grid"><select value={sectionId} onChange={e=>setSectionId(e.target.value)}><option value="">Selecciona sección</option>{sections.data?.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select><input placeholder="Nombre" value={tierName} onChange={e=>setTierName(e.target.value)}/><input type="number" value={tierPrice} onChange={e=>setTierPrice(e.target.value)}/><label>Inicio de venta<input type="datetime-local" value={salesStartAt} onChange={e=>setSalesStartAt(e.target.value)}/></label><label>Fin de venta<input type="datetime-local" value={salesEndAt} onChange={e=>setSalesEndAt(e.target.value)}/></label><button className="button primary" onClick={()=>addTier.mutate()} disabled={!selected||!sectionId}>Crear tier</button></div>{tiers.data?.map(t=><div className="list-row" key={t.id}><span><b>{t.name}</b><small>{t.sectionId}</small></span><b>{formatMoney(t.price,t.currency)}</b></div>)}</section>
 <section className="panel"><h3>Promociones</h3><div className="form-grid"><input placeholder="Código" value={code} onChange={e=>setCode(e.target.value.toUpperCase())}/><input type="number" value={discount} onChange={e=>setDiscount(e.target.value)}/><button className="button primary" onClick={()=>addPromo.mutate()} disabled={!code}>Crear %</button></div>{promos.data?.map(p=><div className="list-row" key={p.id}><span><b>{p.code}</b><small>{p.currentUses} usos</small></span><b>{p.discountValue}%</b></div>)}</section></div></section>
}
