ALTER TABLE venue_sections ADD COLUMN IF NOT EXISTS map_x NUMERIC(10,2);
ALTER TABLE venue_sections ADD COLUMN IF NOT EXISTS map_y NUMERIC(10,2);
ALTER TABLE venue_sections ADD COLUMN IF NOT EXISTS map_width NUMERIC(10,2);
ALTER TABLE venue_sections ADD COLUMN IF NOT EXISTS map_height NUMERIC(10,2);
ALTER TABLE venue_sections ADD COLUMN IF NOT EXISTS map_rotation NUMERIC(10,2) NOT NULL DEFAULT 0;
ALTER TABLE seats ADD COLUMN IF NOT EXISTS map_x NUMERIC(10,2);
ALTER TABLE seats ADD COLUMN IF NOT EXISTS map_y NUMERIC(10,2);
