import { useState, type FormEvent } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import { useAuth } from '../features/auth/AuthContext'
export function RegisterPage() {
  const [firstName,setFirst]=useState(''); const [lastName,setLast]=useState(''); const [email,setEmail]=useState(''); const [password,setPassword]=useState(''); const [error,setError]=useState(''); const [busy,setBusy]=useState(false)
  const {register}=useAuth(); const nav=useNavigate()
  async function submit(e:FormEvent){e.preventDefault();setBusy(true);setError('');try{await register({firstName,lastName,email,password});nav('/events',{replace:true})}catch(e){setError(e instanceof Error?e.message:'No fue posible crear la cuenta')}finally{setBusy(false)}}
  return <main className="auth-page"><section className="panel auth-card"><div className="auth-brand"><span>TF</span></div><span className="eyebrow">Únete a TicketFlow</span><h1>Crea tu cuenta</h1><p className="muted">Compra y administra tus accesos de forma simple.</p><form className="form" onSubmit={submit}><div className="form-row"><label>Nombre<input autoComplete="given-name" required value={firstName} onChange={e=>setFirst(e.target.value)}/></label><label>Apellido<input autoComplete="family-name" required value={lastName} onChange={e=>setLast(e.target.value)}/></label></div><label>Correo electrónico<input type="email" autoComplete="email" placeholder="tu@email.com" required value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Contraseña<input type="password" autoComplete="new-password" minLength={8} required value={password} onChange={e=>setPassword(e.target.value)}/><small className="field-hint">Mínimo 8 caracteres.</small></label><button className="button primary full button-lg" disabled={busy}>{busy?'Creando cuenta…':'Crear cuenta'}</button>{error&&<div className="alert error">{error}</div>}</form><p className="auth-switch">¿Ya tienes cuenta? <Link to="/login">Iniciar sesión</Link></p></section></main>
}
